#!/usr/bin/env python3
"""Build the static, in-browser labforge SIEM demo.

Bakes the canonical Python corpus AND the authoritative detections (computed by
the real ``labforge_siem`` engine) into ``demo/data.js``, then leaves
``demo/index.html`` to render them entirely client-side. Because the data comes
from the same engine the tests cover and the lab runs, the portfolio demo can
never quietly disagree with reality.

Run:
    python demo/build_demo.py
"""
from __future__ import annotations

import json
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(_HERE, "..", "siem"))

from labforge_siem import __version__  # noqa: E402
from labforge_siem.corpus import export_json  # noqa: E402
from labforge_siem.store import LogStore  # noqa: E402
from labforge_siem.corpus import write_corpus  # noqa: E402


def build_data() -> dict:
    bundle = export_json()
    # Compute the authoritative detections with the real engine over a temp
    # materialization of the corpus (identical to what the live SIEM would show).
    import tempfile

    with tempfile.TemporaryDirectory() as tmp:
        write_corpus(tmp)
        dets = LogStore(tmp).detections()
    bundle["detections"] = [
        {
            "rule_id": d.rule_id,
            "title": d.title,
            "severity": d.severity,
            "technique": d.technique,
            "host": d.host,
            "source": d.source,
            "count": d.count,
            "summary": d.summary,
            "evidence": d.evidence,
        }
        for d in dets
    ]
    bundle["version"] = __version__
    return bundle


def main() -> int:
    data = build_data()
    out = os.path.join(_HERE, "data.js")
    with open(out, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("// AUTO-GENERATED by demo/build_demo.py — do not edit by hand.\n")
        fh.write("// Corpus + detections come from the real labforge_siem engine.\n")
        fh.write("window.LABFORGE_DATA = ")
        json.dump(data, fh, indent=2)
        fh.write(";\n")
    n_lines = sum(h["lines"] for h in data["hosts"])
    print(f"wrote {out}: {len(data['hosts'])} hosts, {n_lines} lines, "
          f"{len(data['detections'])} detections (engine v{data['version']})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
