// AUTO-GENERATED by demo/build_demo.py — do not edit by hand.
// Corpus + detections come from the real labforge_siem engine.
window.LABFORGE_DATA = {
  "generated": "2026-07-06T14:00:00+00:00",
  "hosts": [
    {
      "name": "attacker",
      "lines": 2,
      "bytes": 185
    },
    {
      "name": "dvwa",
      "lines": 51,
      "bytes": 6472
    },
    {
      "name": "juice",
      "lines": 30,
      "bytes": 4504
    },
    {
      "name": "siem",
      "lines": 1,
      "bytes": 81
    },
    {
      "name": "victim",
      "lines": 41,
      "bytes": 7077
    }
  ],
  "logs": {
    "attacker": [
      "2026-07-06T14:00:01+00:00 attacker labforge: attacker box provisioned; recon ready",
      "2026-07-06T14:00:33+00:00 attacker nmap: nmap -sS -p- 10.20.0.32 10.20.0.31 10.20.0.40 : scan started"
    ],
    "siem": [
      "2026-07-06T14:00:00+00:00 siem labforge: central collector online (tcp+udp 5514)"
    ],
    "juice": [
      "2026-07-06T14:00:02+00:00 juice systemd: Started labforge target services.",
      "2026-07-06T14:00:31+00:00 juice kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.31 PROTO=TCP SPT=44321 DPT=21 WINDOW=1024 SYN",
      "2026-07-06T14:00:31.050000+00:00 juice kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.31 PROTO=TCP SPT=44321 DPT=22 WINDOW=1024 SYN",
      "2026-07-06T14:00:31.100000+00:00 juice kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.31 PROTO=TCP SPT=44321 DPT=23 WINDOW=1024 SYN",
      "2026-07-06T14:00:31.150000+00:00 juice kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.31 PROTO=TCP SPT=44321 DPT=25 WINDOW=1024 SYN",
      "2026-07-06T14:00:31.200000+00:00 juice kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.31 PROTO=TCP SPT=44321 DPT=53 WINDOW=1024 SYN",
      "2026-07-06T14:00:31.250000+00:00 juice kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.31 PROTO=TCP SPT=44321 DPT=80 WINDOW=1024 SYN",
      "2026-07-06T14:00:31.300000+00:00 juice kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.31 PROTO=TCP SPT=44321 DPT=110 WINDOW=1024 SYN",
      "2026-07-06T14:00:31.350000+00:00 juice kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.31 PROTO=TCP SPT=44321 DPT=139 WINDOW=1024 SYN",
      "2026-07-06T14:00:31.400000+00:00 juice kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.31 PROTO=TCP SPT=44321 DPT=143 WINDOW=1024 SYN",
      "2026-07-06T14:00:31.450000+00:00 juice kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.31 PROTO=TCP SPT=44321 DPT=443 WINDOW=1024 SYN",
      "2026-07-06T14:00:31.500000+00:00 juice kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.31 PROTO=TCP SPT=44321 DPT=445 WINDOW=1024 SYN",
      "2026-07-06T14:00:31.550000+00:00 juice kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.31 PROTO=TCP SPT=44321 DPT=993 WINDOW=1024 SYN",
      "2026-07-06T14:00:31.600000+00:00 juice kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.31 PROTO=TCP SPT=44321 DPT=995 WINDOW=1024 SYN",
      "2026-07-06T14:00:31.650000+00:00 juice kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.31 PROTO=TCP SPT=44321 DPT=1723 WINDOW=1024 SYN",
      "2026-07-06T14:00:31.700000+00:00 juice kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.31 PROTO=TCP SPT=44321 DPT=3306 WINDOW=1024 SYN",
      "2026-07-06T14:00:31.750000+00:00 juice kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.31 PROTO=TCP SPT=44321 DPT=3389 WINDOW=1024 SYN",
      "2026-07-06T14:00:31.800000+00:00 juice kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.31 PROTO=TCP SPT=44321 DPT=5900 WINDOW=1024 SYN",
      "2026-07-06T14:00:31.850000+00:00 juice kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.31 PROTO=TCP SPT=44321 DPT=8000 WINDOW=1024 SYN",
      "2026-07-06T14:00:31.900000+00:00 juice kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.31 PROTO=TCP SPT=44321 DPT=8080 WINDOW=1024 SYN",
      "2026-07-06T14:00:31.950000+00:00 juice kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.31 PROTO=TCP SPT=44321 DPT=8443 WINDOW=1024 SYN",
      "2026-07-06T14:02:40+00:00 juice juice-shop: 10.20.0.10 - - \"GET /admin HTTP/1.1\" 200 210 \"-\" \"Mozilla/5.00 (Nikto/2.5.0) (Evasions:None) (Test:map_codes)\"",
      "2026-07-06T14:02:40.250000+00:00 juice juice-shop: 10.20.0.10 - - \"GET /.git/config HTTP/1.1\" 404 210 \"-\" \"Mozilla/5.00 (Nikto/2.5.0) (Evasions:None) (Test:map_codes)\"",
      "2026-07-06T14:02:40.500000+00:00 juice juice-shop: 10.20.0.10 - - \"GET /robots.txt HTTP/1.1\" 200 210 \"-\" \"Mozilla/5.00 (Nikto/2.5.0) (Evasions:None) (Test:map_codes)\"",
      "2026-07-06T14:02:40.750000+00:00 juice juice-shop: 10.20.0.10 - - \"GET /server-status HTTP/1.1\" 404 210 \"-\" \"Mozilla/5.00 (Nikto/2.5.0) (Evasions:None) (Test:map_codes)\"",
      "2026-07-06T14:02:41+00:00 juice juice-shop: 10.20.0.10 - - \"GET /phpmyadmin/ HTTP/1.1\" 200 210 \"-\" \"Mozilla/5.00 (Nikto/2.5.0) (Evasions:None) (Test:map_codes)\"",
      "2026-07-06T14:02:41.250000+00:00 juice juice-shop: 10.20.0.10 - - \"GET /.env HTTP/1.1\" 404 210 \"-\" \"Mozilla/5.00 (Nikto/2.5.0) (Evasions:None) (Test:map_codes)\"",
      "2026-07-06T14:02:41.500000+00:00 juice juice-shop: 10.20.0.10 - - \"GET /backup.zip HTTP/1.1\" 200 210 \"-\" \"Mozilla/5.00 (Nikto/2.5.0) (Evasions:None) (Test:map_codes)\"",
      "2026-07-06T14:02:41.750000+00:00 juice juice-shop: 10.20.0.10 - - \"GET /ftp HTTP/1.1\" 404 210 \"-\" \"Mozilla/5.00 (Nikto/2.5.0) (Evasions:None) (Test:map_codes)\"",
      "2026-07-06T14:05:00+00:00 juice systemd: labforge health check ok"
    ],
    "dvwa": [
      "2026-07-06T14:00:03+00:00 dvwa systemd: Started labforge target services.",
      "2026-07-06T14:00:30+00:00 dvwa kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.32 PROTO=TCP SPT=44321 DPT=21 WINDOW=1024 SYN",
      "2026-07-06T14:00:30.050000+00:00 dvwa kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.32 PROTO=TCP SPT=44321 DPT=22 WINDOW=1024 SYN",
      "2026-07-06T14:00:30.100000+00:00 dvwa kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.32 PROTO=TCP SPT=44321 DPT=23 WINDOW=1024 SYN",
      "2026-07-06T14:00:30.150000+00:00 dvwa kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.32 PROTO=TCP SPT=44321 DPT=25 WINDOW=1024 SYN",
      "2026-07-06T14:00:30.200000+00:00 dvwa kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.32 PROTO=TCP SPT=44321 DPT=53 WINDOW=1024 SYN",
      "2026-07-06T14:00:30.250000+00:00 dvwa kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.32 PROTO=TCP SPT=44321 DPT=80 WINDOW=1024 SYN",
      "2026-07-06T14:00:30.300000+00:00 dvwa kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.32 PROTO=TCP SPT=44321 DPT=110 WINDOW=1024 SYN",
      "2026-07-06T14:00:30.350000+00:00 dvwa kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.32 PROTO=TCP SPT=44321 DPT=139 WINDOW=1024 SYN",
      "2026-07-06T14:00:30.400000+00:00 dvwa kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.32 PROTO=TCP SPT=44321 DPT=143 WINDOW=1024 SYN",
      "2026-07-06T14:00:30.450000+00:00 dvwa kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.32 PROTO=TCP SPT=44321 DPT=443 WINDOW=1024 SYN",
      "2026-07-06T14:00:30.500000+00:00 dvwa kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.32 PROTO=TCP SPT=44321 DPT=445 WINDOW=1024 SYN",
      "2026-07-06T14:00:30.550000+00:00 dvwa kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.32 PROTO=TCP SPT=44321 DPT=993 WINDOW=1024 SYN",
      "2026-07-06T14:00:30.600000+00:00 dvwa kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.32 PROTO=TCP SPT=44321 DPT=995 WINDOW=1024 SYN",
      "2026-07-06T14:00:30.650000+00:00 dvwa kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.32 PROTO=TCP SPT=44321 DPT=1723 WINDOW=1024 SYN",
      "2026-07-06T14:00:30.700000+00:00 dvwa kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.32 PROTO=TCP SPT=44321 DPT=3306 WINDOW=1024 SYN",
      "2026-07-06T14:00:30.750000+00:00 dvwa kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.32 PROTO=TCP SPT=44321 DPT=3389 WINDOW=1024 SYN",
      "2026-07-06T14:00:30.800000+00:00 dvwa kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.32 PROTO=TCP SPT=44321 DPT=5900 WINDOW=1024 SYN",
      "2026-07-06T14:00:30.850000+00:00 dvwa kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.32 PROTO=TCP SPT=44321 DPT=8000 WINDOW=1024 SYN",
      "2026-07-06T14:00:30.900000+00:00 dvwa kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.32 PROTO=TCP SPT=44321 DPT=8080 WINDOW=1024 SYN",
      "2026-07-06T14:00:30.950000+00:00 dvwa kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.32 PROTO=TCP SPT=44321 DPT=8443 WINDOW=1024 SYN",
      "2026-07-06T14:01:30+00:00 dvwa sshd: Failed password for admin from 10.20.0.10 port 40000 ssh2",
      "2026-07-06T14:01:30.400000+00:00 dvwa sshd: Failed password for root from 10.20.0.10 port 40001 ssh2",
      "2026-07-06T14:01:30.800000+00:00 dvwa sshd: Failed password for gordonb from 10.20.0.10 port 40002 ssh2",
      "2026-07-06T14:01:31.200000+00:00 dvwa sshd: Failed password for 1337 from 10.20.0.10 port 40003 ssh2",
      "2026-07-06T14:01:31.600000+00:00 dvwa sshd: Failed password for pablo from 10.20.0.10 port 40004 ssh2",
      "2026-07-06T14:01:32+00:00 dvwa sshd: Failed password for smithy from 10.20.0.10 port 40005 ssh2",
      "2026-07-06T14:01:32.400000+00:00 dvwa sshd: Failed password for admin from 10.20.0.10 port 40006 ssh2",
      "2026-07-06T14:01:32.800000+00:00 dvwa sshd: Failed password for admin from 10.20.0.10 port 40007 ssh2",
      "2026-07-06T14:01:33.200000+00:00 dvwa sshd: Failed password for root from 10.20.0.10 port 40008 ssh2",
      "2026-07-06T14:01:33.600000+00:00 dvwa sshd: Failed password for gordonb from 10.20.0.10 port 40009 ssh2",
      "2026-07-06T14:01:34+00:00 dvwa sshd: Failed password for 1337 from 10.20.0.10 port 40010 ssh2",
      "2026-07-06T14:01:34.400000+00:00 dvwa sshd: Failed password for pablo from 10.20.0.10 port 40011 ssh2",
      "2026-07-06T14:01:34.800000+00:00 dvwa sshd: Failed password for smithy from 10.20.0.10 port 40012 ssh2",
      "2026-07-06T14:01:35.200000+00:00 dvwa sshd: Failed password for admin from 10.20.0.10 port 40013 ssh2",
      "2026-07-06T14:01:35.600000+00:00 dvwa sshd: Failed password for admin from 10.20.0.10 port 40014 ssh2",
      "2026-07-06T14:01:36+00:00 dvwa sshd: Failed password for root from 10.20.0.10 port 40015 ssh2",
      "2026-07-06T14:01:36.400000+00:00 dvwa sshd: Failed password for gordonb from 10.20.0.10 port 40016 ssh2",
      "2026-07-06T14:01:36.800000+00:00 dvwa sshd: Failed password for 1337 from 10.20.0.10 port 40017 ssh2",
      "2026-07-06T14:01:37.200000+00:00 dvwa sshd: Failed password for pablo from 10.20.0.10 port 40018 ssh2",
      "2026-07-06T14:01:37.600000+00:00 dvwa sshd: Failed password for smithy from 10.20.0.10 port 40019 ssh2",
      "2026-07-06T14:01:38+00:00 dvwa sshd: Failed password for admin from 10.20.0.10 port 40020 ssh2",
      "2026-07-06T14:01:38.400000+00:00 dvwa sshd: Failed password for admin from 10.20.0.10 port 40021 ssh2",
      "2026-07-06T14:01:38.800000+00:00 dvwa sshd: Failed password for root from 10.20.0.10 port 40022 ssh2",
      "2026-07-06T14:01:39.200000+00:00 dvwa sshd: Failed password for gordonb from 10.20.0.10 port 40023 ssh2",
      "2026-07-06T14:01:39.600000+00:00 dvwa sshd: Accepted password for gordonb from 10.20.0.10 port 40099 ssh2",
      "2026-07-06T14:02:20+00:00 dvwa apache2: 10.20.0.10 - - \"GET /vulnerabilities/sqli/?id=1%27&Submit=Submit HTTP/1.1\" 200 4512 \"-\" \"sqlmap/1.8#stable (https://sqlmap.org)\"",
      "2026-07-06T14:02:20.300000+00:00 dvwa apache2: 10.20.0.10 - - \"GET /vulnerabilities/sqli/?id=1%27+AND+1%3D1--+-&Submit=Submit HTTP/1.1\" 200 4512 \"-\" \"sqlmap/1.8#stable (https://sqlmap.org)\"",
      "2026-07-06T14:02:20.600000+00:00 dvwa apache2: 10.20.0.10 - - \"GET /vulnerabilities/sqli/?id=1%27+UNION+SELECT+user%2Cpassword+FROM+users--+-&Submit=Submit HTTP/1.1\" 200 4512 \"-\" \"sqlmap/1.8#stable (https://sqlmap.org)\"",
      "2026-07-06T14:02:20.900000+00:00 dvwa apache2: 10.20.0.10 - - \"GET /vulnerabilities/sqli/?id=1%27+AND+SLEEP%285%29--+-&Submit=Submit HTTP/1.1\" 200 4512 \"-\" \"sqlmap/1.8#stable (https://sqlmap.org)\"",
      "2026-07-06T14:05:00+00:00 dvwa systemd: labforge health check ok"
    ],
    "victim": [
      "2026-07-06T14:00:04+00:00 victim systemd: Started labforge target services.",
      "2026-07-06T14:00:32+00:00 victim kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.40 PROTO=TCP SPT=44321 DPT=21 WINDOW=1024 SYN",
      "2026-07-06T14:00:32.050000+00:00 victim kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.40 PROTO=TCP SPT=44321 DPT=22 WINDOW=1024 SYN",
      "2026-07-06T14:00:32.100000+00:00 victim kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.40 PROTO=TCP SPT=44321 DPT=23 WINDOW=1024 SYN",
      "2026-07-06T14:00:32.150000+00:00 victim kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.40 PROTO=TCP SPT=44321 DPT=25 WINDOW=1024 SYN",
      "2026-07-06T14:00:32.200000+00:00 victim kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.40 PROTO=TCP SPT=44321 DPT=53 WINDOW=1024 SYN",
      "2026-07-06T14:00:32.250000+00:00 victim kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.40 PROTO=TCP SPT=44321 DPT=80 WINDOW=1024 SYN",
      "2026-07-06T14:00:32.300000+00:00 victim kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.40 PROTO=TCP SPT=44321 DPT=110 WINDOW=1024 SYN",
      "2026-07-06T14:00:32.350000+00:00 victim kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.40 PROTO=TCP SPT=44321 DPT=139 WINDOW=1024 SYN",
      "2026-07-06T14:00:32.400000+00:00 victim kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.40 PROTO=TCP SPT=44321 DPT=143 WINDOW=1024 SYN",
      "2026-07-06T14:00:32.450000+00:00 victim kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.40 PROTO=TCP SPT=44321 DPT=443 WINDOW=1024 SYN",
      "2026-07-06T14:00:32.500000+00:00 victim kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.40 PROTO=TCP SPT=44321 DPT=445 WINDOW=1024 SYN",
      "2026-07-06T14:00:32.550000+00:00 victim kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.40 PROTO=TCP SPT=44321 DPT=993 WINDOW=1024 SYN",
      "2026-07-06T14:00:32.600000+00:00 victim kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.40 PROTO=TCP SPT=44321 DPT=995 WINDOW=1024 SYN",
      "2026-07-06T14:00:32.650000+00:00 victim kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.40 PROTO=TCP SPT=44321 DPT=1723 WINDOW=1024 SYN",
      "2026-07-06T14:00:32.700000+00:00 victim kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.40 PROTO=TCP SPT=44321 DPT=3306 WINDOW=1024 SYN",
      "2026-07-06T14:00:32.750000+00:00 victim kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.40 PROTO=TCP SPT=44321 DPT=3389 WINDOW=1024 SYN",
      "2026-07-06T14:00:32.800000+00:00 victim kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.40 PROTO=TCP SPT=44321 DPT=5900 WINDOW=1024 SYN",
      "2026-07-06T14:00:32.850000+00:00 victim kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.40 PROTO=TCP SPT=44321 DPT=8000 WINDOW=1024 SYN",
      "2026-07-06T14:00:32.900000+00:00 victim kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.40 PROTO=TCP SPT=44321 DPT=8080 WINDOW=1024 SYN",
      "2026-07-06T14:00:32.950000+00:00 victim kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.40 PROTO=TCP SPT=44321 DPT=8443 WINDOW=1024 SYN",
      "2026-07-06T14:03:20+00:00 victim labforge: EventID=4625 An account failed to log on. Account: labuser  Source Network Address: 10.20.0.10  Logon Type: 10 (RemoteInteractive)  Status: 0xC000006D",
      "2026-07-06T14:03:20.500000+00:00 victim labforge: EventID=4625 An account failed to log on. Account: administrator  Source Network Address: 10.20.0.10  Logon Type: 10 (RemoteInteractive)  Status: 0xC000006D",
      "2026-07-06T14:03:21+00:00 victim labforge: EventID=4625 An account failed to log on. Account: svc_backup  Source Network Address: 10.20.0.10  Logon Type: 10 (RemoteInteractive)  Status: 0xC000006D",
      "2026-07-06T14:03:21.500000+00:00 victim labforge: EventID=4625 An account failed to log on. Account: guest  Source Network Address: 10.20.0.10  Logon Type: 10 (RemoteInteractive)  Status: 0xC000006D",
      "2026-07-06T14:03:22+00:00 victim labforge: EventID=4625 An account failed to log on. Account: labuser  Source Network Address: 10.20.0.10  Logon Type: 10 (RemoteInteractive)  Status: 0xC000006D",
      "2026-07-06T14:03:22.500000+00:00 victim labforge: EventID=4625 An account failed to log on. Account: labuser  Source Network Address: 10.20.0.10  Logon Type: 10 (RemoteInteractive)  Status: 0xC000006D",
      "2026-07-06T14:03:23+00:00 victim labforge: EventID=4625 An account failed to log on. Account: administrator  Source Network Address: 10.20.0.10  Logon Type: 10 (RemoteInteractive)  Status: 0xC000006D",
      "2026-07-06T14:03:23.500000+00:00 victim labforge: EventID=4625 An account failed to log on. Account: svc_backup  Source Network Address: 10.20.0.10  Logon Type: 10 (RemoteInteractive)  Status: 0xC000006D",
      "2026-07-06T14:03:24+00:00 victim labforge: EventID=4625 An account failed to log on. Account: guest  Source Network Address: 10.20.0.10  Logon Type: 10 (RemoteInteractive)  Status: 0xC000006D",
      "2026-07-06T14:03:24.500000+00:00 victim labforge: EventID=4625 An account failed to log on. Account: labuser  Source Network Address: 10.20.0.10  Logon Type: 10 (RemoteInteractive)  Status: 0xC000006D",
      "2026-07-06T14:03:25+00:00 victim labforge: EventID=4625 An account failed to log on. Account: labuser  Source Network Address: 10.20.0.10  Logon Type: 10 (RemoteInteractive)  Status: 0xC000006D",
      "2026-07-06T14:03:25.500000+00:00 victim labforge: EventID=4625 An account failed to log on. Account: administrator  Source Network Address: 10.20.0.10  Logon Type: 10 (RemoteInteractive)  Status: 0xC000006D",
      "2026-07-06T14:03:26+00:00 victim labforge: EventID=4625 An account failed to log on. Account: svc_backup  Source Network Address: 10.20.0.10  Logon Type: 10 (RemoteInteractive)  Status: 0xC000006D",
      "2026-07-06T14:03:26.500000+00:00 victim labforge: EventID=4625 An account failed to log on. Account: guest  Source Network Address: 10.20.0.10  Logon Type: 10 (RemoteInteractive)  Status: 0xC000006D",
      "2026-07-06T14:03:27+00:00 victim labforge: EventID=4625 An account failed to log on. Account: labuser  Source Network Address: 10.20.0.10  Logon Type: 10 (RemoteInteractive)  Status: 0xC000006D",
      "2026-07-06T14:03:27.500000+00:00 victim labforge: EventID=4625 An account failed to log on. Account: labuser  Source Network Address: 10.20.0.10  Logon Type: 10 (RemoteInteractive)  Status: 0xC000006D",
      "2026-07-06T14:03:28+00:00 victim labforge: EventID=4625 An account failed to log on. Account: administrator  Source Network Address: 10.20.0.10  Logon Type: 10 (RemoteInteractive)  Status: 0xC000006D",
      "2026-07-06T14:03:28.500000+00:00 victim labforge: EventID=4625 An account failed to log on. Account: svc_backup  Source Network Address: 10.20.0.10  Logon Type: 10 (RemoteInteractive)  Status: 0xC000006D",
      "2026-07-06T14:03:29+00:00 victim labforge: EventID=4624 An account was successfully logged on. Account: labuser  Source Network Address: 10.20.0.10  Logon Type: 10 (RemoteInteractive)",
      "2026-07-06T14:03:29.500000+00:00 victim labforge: EventID=4672 Special privileges assigned to new logon. Account: labuser  Source Network Address: 10.20.0.10"
    ]
  },
  "detections": [
    {
      "rule_id": "logon-after-brute",
      "title": "Logon after brute force",
      "severity": "critical",
      "technique": "T1110",
      "host": "victim",
      "source": "10.20.0.10",
      "count": 1,
      "summary": "Successful logon (4624) on victim after 18 failures \u2014 possible brute-force success.",
      "evidence": [
        "2026-07-06T14:03:29+00:00 victim labforge: EventID=4624 An account was successfully logged on. Account: labuser  Source Network Address: 10.20.0.10  Logon Type: 10 (RemoteInteractive)"
      ]
    },
    {
      "rule_id": "ssh-brute-force",
      "title": "SSH brute force",
      "severity": "high",
      "technique": "T1110",
      "host": "dvwa",
      "source": "10.20.0.10",
      "count": 24,
      "summary": "24 failed SSH logins from 10.20.0.10 on dvwa \u2014 likely password spraying / hydra.",
      "evidence": [
        "2026-07-06T14:01:30+00:00 dvwa sshd: Failed password for admin from 10.20.0.10 port 40000 ssh2",
        "2026-07-06T14:01:30.400000+00:00 dvwa sshd: Failed password for root from 10.20.0.10 port 40001 ssh2",
        "2026-07-06T14:01:30.800000+00:00 dvwa sshd: Failed password for gordonb from 10.20.0.10 port 40002 ssh2",
        "2026-07-06T14:01:31.200000+00:00 dvwa sshd: Failed password for 1337 from 10.20.0.10 port 40003 ssh2"
      ]
    },
    {
      "rule_id": "rdp-brute-force",
      "title": "RDP/Windows brute force",
      "severity": "high",
      "technique": "T1110",
      "host": "victim",
      "source": "10.20.0.10",
      "count": 18,
      "summary": "18 Windows failed-logon (4625) events from 10.20.0.10 on victim \u2014 RDP/SMB brute force.",
      "evidence": [
        "2026-07-06T14:03:20+00:00 victim labforge: EventID=4625 An account failed to log on. Account: labuser  Source Network Address: 10.20.0.10  Logon Type: 10 (RemoteInteractive)  Status: 0xC000006D",
        "2026-07-06T14:03:20.500000+00:00 victim labforge: EventID=4625 An account failed to log on. Account: administrator  Source Network Address: 10.20.0.10  Logon Type: 10 (RemoteInteractive)  Status: 0xC000006D",
        "2026-07-06T14:03:21+00:00 victim labforge: EventID=4625 An account failed to log on. Account: svc_backup  Source Network Address: 10.20.0.10  Logon Type: 10 (RemoteInteractive)  Status: 0xC000006D",
        "2026-07-06T14:03:21.500000+00:00 victim labforge: EventID=4625 An account failed to log on. Account: guest  Source Network Address: 10.20.0.10  Logon Type: 10 (RemoteInteractive)  Status: 0xC000006D"
      ]
    },
    {
      "rule_id": "sqlmap-scan",
      "title": "sqlmap injection scan",
      "severity": "high",
      "technique": "T1190",
      "host": "dvwa",
      "source": "10.20.0.10",
      "count": 4,
      "summary": "4 sqlmap injection scan request(s) from 10.20.0.10 against dvwa.",
      "evidence": [
        "2026-07-06T14:02:20+00:00 dvwa apache2: 10.20.0.10 - - \"GET /vulnerabilities/sqli/?id=1%27&Submit=Submit HTTP/1.1\" 200 4512 \"-\" \"sqlmap/1.8#stable (https://sqlmap.org)\"",
        "2026-07-06T14:02:20.300000+00:00 dvwa apache2: 10.20.0.10 - - \"GET /vulnerabilities/sqli/?id=1%27+AND+1%3D1--+-&Submit=Submit HTTP/1.1\" 200 4512 \"-\" \"sqlmap/1.8#stable (https://sqlmap.org)\"",
        "2026-07-06T14:02:20.600000+00:00 dvwa apache2: 10.20.0.10 - - \"GET /vulnerabilities/sqli/?id=1%27+UNION+SELECT+user%2Cpassword+FROM+users--+-&Submit=Submit HTTP/1.1\" 200 4512 \"-\" \"sqlmap/1.8#stable (https://sqlmap.org)\"",
        "2026-07-06T14:02:20.900000+00:00 dvwa apache2: 10.20.0.10 - - \"GET /vulnerabilities/sqli/?id=1%27+AND+SLEEP%285%29--+-&Submit=Submit HTTP/1.1\" 200 4512 \"-\" \"sqlmap/1.8#stable (https://sqlmap.org)\""
      ]
    },
    {
      "rule_id": "port-sweep",
      "title": "nmap port sweep",
      "severity": "medium",
      "technique": "T1046",
      "host": "dvwa",
      "source": "10.20.0.10",
      "count": 60,
      "summary": "10.20.0.10 probed 20 distinct ports \u2014 nmap-style port sweep against dvwa.",
      "evidence": [
        "2026-07-06T14:00:30+00:00 dvwa kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.32 PROTO=TCP SPT=44321 DPT=21 WINDOW=1024 SYN",
        "2026-07-06T14:00:30.050000+00:00 dvwa kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.32 PROTO=TCP SPT=44321 DPT=22 WINDOW=1024 SYN",
        "2026-07-06T14:00:30.100000+00:00 dvwa kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.32 PROTO=TCP SPT=44321 DPT=23 WINDOW=1024 SYN",
        "2026-07-06T14:00:30.150000+00:00 dvwa kernel: [labforge-nft] SYN-scan IN=eth1 SRC=10.20.0.10 DST=10.20.0.32 PROTO=TCP SPT=44321 DPT=25 WINDOW=1024 SYN"
      ]
    },
    {
      "rule_id": "nikto-scan",
      "title": "nikto web scan",
      "severity": "medium",
      "technique": "T1595",
      "host": "juice",
      "source": "10.20.0.10",
      "count": 8,
      "summary": "8 nikto web scan request(s) from 10.20.0.10 against juice.",
      "evidence": [
        "2026-07-06T14:02:40+00:00 juice juice-shop: 10.20.0.10 - - \"GET /admin HTTP/1.1\" 200 210 \"-\" \"Mozilla/5.00 (Nikto/2.5.0) (Evasions:None) (Test:map_codes)\"",
        "2026-07-06T14:02:40.250000+00:00 juice juice-shop: 10.20.0.10 - - \"GET /.git/config HTTP/1.1\" 404 210 \"-\" \"Mozilla/5.00 (Nikto/2.5.0) (Evasions:None) (Test:map_codes)\"",
        "2026-07-06T14:02:40.500000+00:00 juice juice-shop: 10.20.0.10 - - \"GET /robots.txt HTTP/1.1\" 200 210 \"-\" \"Mozilla/5.00 (Nikto/2.5.0) (Evasions:None) (Test:map_codes)\"",
        "2026-07-06T14:02:40.750000+00:00 juice juice-shop: 10.20.0.10 - - \"GET /server-status HTTP/1.1\" 404 210 \"-\" \"Mozilla/5.00 (Nikto/2.5.0) (Evasions:None) (Test:map_codes)\""
      ]
    }
  ],
  "version": "1.1.0"
};
